ş SCENARIO FILE format1 Copyright 1994 TECHNICAL ARTS h.godai
6brand
;15
7
Aname “c“‡—³”V‰î
Bop2
G3
6logom-1
G1
6logom-2
6logom-3
6logom-4
6logom-0
G3
6logom
6logot
G0
;30
G255
;30
+
ÿWelcome to "Rules of Pleasure!" 
ÿIn order to advance, you may give a name..Your name is $name .
ÿ
ÿ
ÿ
ÿ
ÿ
ÿ
ÿ
ÿIs this name acceptable?
ÿ
ÿ
ÿ"NameEntry1
'Yes     
(NOX‚    ¢
>2
#00000384
$00000537
!*
+
ÿPlease enter a new name          
Name: 
Ename
ÿYour name is Íu$namev
ÿ
ÿ
ÿ
ÿIs this nameok?
ÿ
ÿ"NameEntry2
'Yes¢
(No    
>2
#00000537
$00000384
!*
G0
Fkairaku.sc
64
